import type { Opportunity } from "./types";

// Sample opportunities for NEXT_PUBLIC_DEMO=1 — lets the dashboard be previewed and
// QA'd with no Supabase connection. Numbers are internally consistent with calc.py.
export const DEMO_OPPORTUNITIES: Opportunity[] = [
  {
    id: "demo-1",
    model_score: 5180,
    model_confidence: 0.64,
    created_at: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    updated_at: new Date().toISOString(),
    scraped_item_id: "s1",
    title: "Heidelberg Printmaster QM 46-2 Commercial Offset Press",
    source: "govdeals",
    source_url: "https://www.govdeals.com/",
    model_number: "QM 46-2",
    brand: "Heidelberg",
    condition: "Used - Working",
    image_url: null,
    ask_price: 4200,
    target_sell_price: 9850,
    freight_cost: 250,
    platform_fee: 295.5,
    processing_fee: 295.5,
    insurance_fee: 59.1,
    total_cost: 5100.1,
    net_profit: 4749.9,
    roi: 1.1309,
    sold_count_30d: 6,
    adv: 0.2,
    est_days_to_liquidate: 5,
    liquidity_ok: true,
    comps: [
      { title: "Heidelberg QM 46-2", sold_price: 9900, sold_date: "2026-06-02", url: "#" },
      { title: "Heidelberg Printmaster 46", sold_price: 9800, sold_date: "2026-05-28", url: "#" },
      { title: "Heidelberg QM46", sold_price: 9850, sold_date: "2026-05-21", url: "#" },
    ],
    status: "new",
  },
  {
    id: "demo-2",
    model_score: 1610,
    model_confidence: 0.48,
    created_at: new Date(Date.now() - 1000 * 60 * 42).toISOString(),
    updated_at: new Date().toISOString(),
    scraped_item_id: "s2",
    title: "Hobart HL600 60 Qt Commercial Planetary Mixer",
    source: "govdeals",
    source_url: "https://www.govdeals.com/",
    model_number: "HL600",
    brand: "Hobart",
    condition: "Used",
    image_url: null,
    ask_price: 1800,
    target_sell_price: 4100,
    freight_cost: 250,
    platform_fee: 123,
    processing_fee: 123,
    insurance_fee: 24.6,
    total_cost: 2320.6,
    net_profit: 1779.4,
    roi: 0.9886,
    sold_count_30d: 4,
    adv: 0.1333,
    est_days_to_liquidate: 7.5,
    liquidity_ok: true,
    comps: [
      { title: "Hobart HL600 Legacy", sold_price: 4200, sold_date: "2026-06-01", url: "#" },
      { title: "Hobart HL600", sold_price: 4050, sold_date: "2026-05-25", url: "#" },
      { title: "Hobart Legacy 60qt", sold_price: 4050, sold_date: "2026-05-19", url: "#" },
    ],
    status: "reviewing",
  },
  {
    id: "demo-3",
    model_score: 470,
    model_confidence: 0,
    created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    updated_at: new Date().toISOString(),
    scraped_item_id: "s3",
    title: "Thermo Scientific Sorvall ST 16R Refrigerated Centrifuge",
    source: "govdeals",
    source_url: "https://www.govdeals.com/",
    model_number: "ST 16R",
    brand: "Thermo Scientific",
    condition: "For parts or repair",
    image_url: null,
    ask_price: 2600,
    target_sell_price: 3550,
    freight_cost: 250,
    platform_fee: 106.5,
    processing_fee: 106.5,
    insurance_fee: 21.3,
    total_cost: 3084.3,
    net_profit: 465.7,
    roi: 0.1791,
    sold_count_30d: 3,
    adv: 0.1,
    est_days_to_liquidate: 10,
    liquidity_ok: true,
    comps: [
      { title: "Sorvall ST 16R", sold_price: 3600, sold_date: "2026-05-30", url: "#" },
      { title: "Thermo ST16R", sold_price: 3500, sold_date: "2026-05-22", url: "#" },
      { title: "Sorvall ST 16R Refurb", sold_price: 3550, sold_date: "2026-05-15", url: "#" },
    ],
    status: "new",
  },
];
